### ISSUE TITLE
[FEATURE] PreInsertSignal

### ISSUE THREAD

**Issue by lochmueller** [frappant/frp_form_answers#1]
Hey folks,

thanks for the great work. It would be cool, if there is a Signal in Front of the Insert ( https://github.com/frappant/frp_form_answers/blob/master/Classes/Domain/Finishers/SaveFormToDatabaseFinisher.php#L46 ) to add custom Meta-Data like (IP address, Client information, time stamps or other information).

Regards,
Tim

**Comment by lochmueller** [comment]
[patch.txt](https://github.com/frappant/frp_form_answers/files/1310656/patch.txt)

**Comment by Wh0l3** [comment]
I added a slotdispatcher in the finisher - hopefully it helps you with your development.

**Comment by lochmueller** [comment]
Thanks... I close this issue!
