### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by r3h6** [frappant/frp_form_answers#12]
Please move all text to localization files and check spelling.
Also provide a German translation.

**Comment by dkm-bb** [comment]
Instead of telling the developer to do that, you could do it yourself and create a pull request?

**Comment by Wh0l3** [comment]
He's a coworker of mine... it's my job, he's the tester. 
But thank you for your effort :)

**Comment by maciejszklarczyk** [comment]
I am starting to work on it. Just give me some time ;)
