### ISSUE TITLE
Non admin user can't access the backend module

### ISSUE THREAD

**Issue by dkm-bb** [frappant/frp_form_answers#16]
Hi

I'm seeing this error when using the backend module as a non-admin user:

Oops, an error occurred!
Class 'Frappant\FrpFormAnswers\Utility\PageRepository' not found

It looks like a namespace is missing from versioned/web/typo3conf/ext/frp_form_answers/Classes/Utility/BackendUtility.php line 40

TYPO3 8.7.9

**Comment by Wh0l3** [comment]
Namespace is added in Version 1.1.0 which I uploaded recently
