### ISSUE TITLE
Undefined method setSubmitUid()

### ISSUE THREAD

**Issue by RinyVT** [frappant/frp_form_answers#17]
Version: 1.1.0

When submitting a form, there's a fatal exception:
"Call to undefined method Frappant\FrpFormAnswers\Domain\Model\FormEntry::setSubmitUid()"

This function (and the getter) is used in the finisher and in the exporter, but FormEntry doesn't have a setSubmitUid and getSubmitUid?

Edit: I see it has been fixed in master.. Just no new version yet

**Comment by Wh0l3** [comment]
Included that
