### ISSUE TITLE
missing option to grant non-admins to show up a single record

### ISSUE THREAD

**Issue by wini2** [frappant/frp_form_answers#19]
i don't know if it is a bug or a feature. even i give every right i can find in be-user-permission setting (show modul, table listing and table modify and everything at  allowed excludefields) to a non-admin, this be-user can't open a single record like an admin can. export seems to be o.k.

**Comment by Wh0l3** [comment]
I tried to reproduce your bug - and yes, it is a bug. With my backend user, who is an editor. I could open the form entries after giving acess&edit rights on the table and its field (and the Backend Module).
Can you describe what you tried? On which version are you?

**Comment by wini2** [comment]
thanks for your instant reply. TYPO3-Version is 8.7.20, frp_form_answers-Version is 1.2.0.

as an admin i can open a single entry, as a non-admin the list shows up but i cant open the single record "Edit Form Entry "X" on page..."

![list](https://user-images.githubusercontent.com/6897742/48413454-1b828400-e748-11e8-91e8-5f17c86b4690.jpg)

![entry](https://user-images.githubusercontent.com/6897742/48413574-6c927800-e748-11e8-8d78-b60b106da348.jpg)


be-user-group has access-rights to Form Entry Module and table listing and modify. These are the Allowed excludefields-settings.
![be-user-group-settings](https://user-images.githubusercontent.com/6897742/48413508-3b19ac80-e748-11e8-94db-be9ac5e46949.jpg)

**Comment by wini2** [comment]
it don' know  what went wrong - but the problem vanished after adjusting access rights (admin tools access-module). so i think, it was my fault.
