### ISSUE TITLE
Upload fields: value not saved

### ISSUE THREAD

**Issue by klodeckl** [frappant/frp_form_answers#20]
On upload fields, the filename should be saved in the log entry (atm no value is saved on upload fields).

**Comment by Wh0l3** [comment]
That's true because this type of input field is not handled... I'll update that this week

**Comment by AstCommodore** [comment]
Maybe, the following error belongs to this issue. When using upload fields which aren't required the finisher throws an exception:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function getOriginalResource() on null | Error thrown in file typo3conf/ext/frp_form_answers/Classes/Domain/Finishers/SaveFormToDatabaseFinisher.php in line 84.

Didn't dick deep into the code, so it's a first notice. ;)

**Comment by Wh0l3** [comment]
@AstCommodore Fixed it with version 4.0.2
