### ISSUE TITLE
Fatal error including phpexcel.phar

### ISSUE THREAD

**Issue by AstCommodore** [frappant/frp_form_answers#22]
If phpexel is missing, the ext_tables.php includes phpexcel.phar by itself. The inclusion will fail (see also https://forge.typo3.org/issues/85658):

```
Warning: Uncaught TYPO3\PharStreamWrapper\Exception: Executing phar:///home/www/p464626/html/typo3/typo3conf/ext/frp_form_answers/Resources/Private/Vendors/phpexcel.phar/vendor/autoload.php is denied in /html/typo3/typo3/sysext/core/Classes/IO/PharStreamWrapperInterceptor.php:39 Stack trace: #0 /html/typo3/vendor/typo3/phar-stream-wrapper/src/Behavior.php(72): TYPO3\CMS\Core\IO\PharStreamWrapperInterceptor->assert('phar:///home/ww...', 'stream_open') #1 /html/typo3/vendor/typo3/phar-stream-wrapper/src/Manager.php(110): TYPO3\PharStreamWrapper\Behavior->assert('phar:///home/ww...', 'stream_open') #2 /html/typo3/vendor/typo3/phar-stream-wrapper/src/PharStreamWrapper.php(421): TYPO3\PharStreamWrapper\Manager->assert('phar:///home/ww...', 'stream_open') #3 /html/typo3/vendor/typo3/phar-stream-wrapper/src/PharStreamWrapper.php(256): TYPO3\PharStreamWrapper\PharStreamWrapper->assert('phar:///home/ww...', 'stream_open') #4 /html/typo3/typo3conf/ext/frp_form_answers/ext_tables.php(30): TYPO3\PharStreamWrapper\PharStreamWrappe in /html/typo3/typo3/sysext/core/Classes/IO/PharStreamWrapperInterceptor.php on line 39

Fatal error: TYPO3\CMS\Core\Utility\ExtensionManagementUtility::main(): Failed opening required 'phar:///home/www/p464626/html/typo3/typo3conf/ext/frp_form_answers/Resources/Private/Vendors/phpexcel.phar/vendor/autoload.php' (include_path='.:') in /html/typo3/typo3conf/ext/frp_form_answers/ext_tables.php on line 30

```

Just use `ExtensionManagementUtility::extPath` instead of `getFileAbsFileName`:

`include_once 'phar://' . \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath($_EXTKEY) . '/Resources/Private/Vendors/phpexcel.phar/vendor/autoload.php';`

**Comment by joka123** [comment]
didn't work i got the following arror after changing to ExtensionManagementUtility::extPath

#1530103998: Executing phar:///www/.../typo3-8-test/typo3conf/ext/frp_form_answers/Resources/Private/Vendors/phpexcel.phar/vendor/autoload.php is denied

**Comment by Wh0l3** [comment]
@AstCommodore: I inserted your recommendation.
@joka123: I will test it this week, maybe I will find out why this did not work for you

**Comment by AstCommodore** [comment]
@Wh0l3 I thought it is the solution and I tested the change successfully at hoster Mittwald Medien. But one day later (maybe after automatic cache clearing), I've got the same error like @joka123 .

Mittwald and me figure out, was wrong – it's the recommended way, see https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.6.x/Important-85385-IntegratePharStreamWrapper.html

**Comment by AstCommodore** [comment]
Ok, an typical answer of a hoster:
They mean, because of ending support for PHPEcxel after PHP 7.0 it doesn't matter if you use the Phar – it won't work. Better switch to https://github.com/PHPOffice/PhpSpreadsheet as PHPEcxel successor ...

I don't know how much work it is to switch to PhpSpreadsheet, but it might be a good solution for a new extension version which recommends PHP 7.2 and TYPO3 9.5.

What's your meaning?

**Comment by Wh0l3** [comment]
Seems reasonable.
"PHPExcel last version, 1.8.1, was released in 2015. The project was officially deprecated in 2017 and permanently archived in 2019." is what I found on their Github site.

So I'll update this extension to the new library PhpSpreadsheet.

**Comment by joka123** [comment]
I've done this before, if you're interested.
https://github.com/joka123/frp_form_answers_spreadsheet

i have to clear all caches and recreate the autoload dump in install tool

**Comment by AstCommodore** [comment]
Just tested with regression bugfix version 8.7.26 and it seems to be working again! Just stumbled over issue 58c40c1356 and ff2b828032 in https://get.typo3.org/release-notes/8.7.26 and wanted to test.

**Comment by ZYZ64738** [comment]
For me it doesn't work:

None of these lines inside ext_tables.php do work (MIttwald  Typo3 .8.7.26 |  frp_form_answers 1.2.0)

#       require_once 'phar://'.\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath($_EXTKEY).'/Resources/Private/Vendors/phpexcel.phar/vendor/autoload.php';

#       require_once 'phar://'.\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('frp_form_answers').'/Resources/Private/Vendors/phpexcel.phar/vendor/autoload.php';

#    require_once 'phar://'.\TYPO3\CMS\Core\Utility\GeneralUtility::getFileAbsFileName('EXT:'.$_EXTKEY.'/Resources/Private/Vendors/phpexcel.phar/vendor/autoload.php');

**Comment by Wh0l3** [comment]
I made a version based on @joka123 - thanks for the great work!
It's in a feature (PhpSpreadSheet), I'll merge it after some more tests
