### ISSUE TITLE
is there a button to delete all records ? 

### ISSUE THREAD

**Issue by celmedia** [frappant/frp_form_answers#23]
hey ... thanks so mouch for the extension ... i was wondering if there is a easy posibility to delete all entries ... or where do i finde the data ?

**Comment by Wh0l3** [comment]
At this moment, you have to go direct into the database and delete them there.
Good idea for a new feature

**Comment by celmedia** [comment]
ahh perfect ... found it ... was looking for it but didnt found it over search ... but found it after in tabel tx_frpformanswers_domain_model_formentry ... thanks a lot
