### ISSUE TITLE
typo3 v10 is there a released planned ? 

### ISSUE THREAD

**Issue by celmedia** [frappant/frp_form_answers#26]
after updating from typo3 v9 to v10 i get the error when i try to login to backend that the icon is missing : 
(1/1) #1460976566 InvalidArgumentException
[module-web_FrpFormAnswersFormanswers] The option "source" is required and must not be empty

https://wiki.typo3.org/Exception/CMS/1460976566

is there a update planed for typo3 v 10 ? or somebody can help me to make it run also with typo3 v10 ? 
thanks allready in advance

**Comment by Wh0l3** [comment]
There is a releasebranch 3.0.0
I haven't tried images so far. If they fail there too, i'll correct that.
Beside that, my workmate is on the tests.

**Comment by celmedia** [comment]
ooo sorrry ... didnt saw the branch 3 .... just checked the basics ... workes great and love it as mouch as before ... :-) thank you guys for that awesome great work your doing... super simply nice work

**Comment by pniederlag** [comment]
Thx for providing the update!

As 10.x is spreading around, is there anyone around to tag and ship a release to ter/packagist?

**Comment by Wh0l3** [comment]
That should be done, you're right... I set that to tomorrow.

**Comment by pniederlag** [comment]
Hi, thx for looking into this and updating it, greatly appreciated! Would be awesome if you could also add a git tag for 3.0.0 in this repository.
