### ISSUE TITLE
 PHP Warning: Invalid argument supplied for foreach() in: Frappant\FrpFormAnswers\Utility\UserFieldUtility

### ISSUE THREAD

**Issue by guelzow** [frappant/frp_form_answers#3]
Hi everyone.

When you create a new record by hand in the backend, you get a PHP Warning: Invalid argument supplied for foreach() in:
Frappant\FrpFormAnswers\Utility\UserFieldUtility

**What is happening in the code:**
In Line 12, the $fieldValues may be NULL.

**How to reproduce**:
1.) Setup a new TYPO3
2.) Install the extension
3.) Create a new record in the backend by hand.

**System:**
- TYPO3 8.7
- PHP 7.1

Tobi

**Comment by Wh0l3** [comment]
I added a check around there, so the error should not be thrown anymore.
The fields are not writable, because that would mean that you can change the form answers.
