### ISSUE TITLE
Backend module not accessible in TYPO3 10

### ISSUE THREAD

**Issue by dkm-bb** [frappant/frp_form_answers#36]
Hi

I installed the extension on a site running TYPO3 10.4.9 but it returns an error.

Class 'Frappant\FrpFormAnswers\ViewHelpers\Be\Link\UriBuilder' not found

This is easily fixed by including this line at the top:

use TYPO3\CMS\Backend\Routing\UriBuilder;

**Comment by sascha-schieferdecker** [comment]
Still not working correctly if in PHP is configured to throw warnings:

![image](https://user-images.githubusercontent.com/8793359/105325466-e9dd9100-5bcc-11eb-8eec-05117acd36d2.png)

Fix is to use correct quotes in Line 83 of BeLinkViewHelper.php. I'll create a pull request.
