### ISSUE TITLE
PageRepository not injected

### ISSUE THREAD

**Issue by majdothman** [frappant/frp_form_answers#52]
https://github.com/frappant/frp_form_answers/blob/cb97379b365b86452fdf88751c785afc1e415e93/Classes/Controller/FormEntryController.php#L96

    private PageRepository $pageRepository;
    
    public function injectPageRepository(PageRepository $pageRepository): void
    {
        $this->pageRepository = $pageRepository;
    }

**Comment by frpuser** [comment]
Thanks for the hint.
the pageRepository was inserted with version 4.0.1.
