### ISSUE TITLE
Call to a member function check() on null 

### ISSUE THREAD

**Issue by r3h6** [frappant/frp_form_answers#6]
In Frontend on a site with a form:

Call to a member function check() on null 

Error thrown in file
/var/www/web/typo3conf/ext/frp_form_answers/Classes/Condition/BeUserHasAccessRightsCondition.php in line 16.

**Comment by Wh0l3** [comment]
Better check - if $GLOBALS["BE_USER"] is no object, return false

**Comment by r3h6** [comment]
Seems to be ok
