### ISSUE TITLE
Release 4.1.0

### ISSUE THREAD

**Issue by SomeBdyElse** [frappant/frp_form_answers#64]
Hi @jonashirschi !

I can see that you merged the release/4.1.0 branch but I do not find a 4.1.0 tag. Did you maybe forget to tag?

**Comment by jonashirschi** [comment]
Thanks for the hint
I have just added the tag.

**Comment by SomeBdyElse** [comment]
Hi @jonashirschi ! Thank you for pushing that tag. Unfortunately packagist did not pick it up yet, as the package is not configured for auto-update. 

https://packagist.org/packages/frappant/frp-form-answers#4.0.2
> This package is not [auto-updated](https://packagist.org/about#how-to-update-packages).

Please be so kind and notify packagist of the update.
