### ISSUE TITLE
Exception on first click on backend module

### ISSUE THREAD

**Issue by r3h6** [frappant/frp_form_answers#7]
Following error occurs when no page is selected in tree.

#1484828466: The IN operator needs a non-empty value list to compare against. The given value list is empty. (More information)

Somehow related to fetch data from the db.

23 TYPO3\CMS\Extbase\Persistence\Generic\Storage\Typo3DbQueryParser::parseDynamicOperand(TYPO3\CMS\Extbase\Persistence\Generic\Qom\Comparison, TYPO3\CMS\Extbase\Persistence\Generic\Qom\Selector)
14 Frappant\FrpFormAnswers\Controller\FormEntryController::listAction()

**Comment by Wh0l3** [comment]
Loaded first web page (getFirstWebpage from core page repository) if pid is 0

**Comment by r3h6** [comment]
ok
